swagger: "2.0"
info:
  title: Dev Bootcamp Rest API
  description: Documentaci贸n para la restful api
  version: 1.0.0
host: localhost:3000
basePath: /api
tags:
  - name: Registro de nuevo usuario
    description: API para registro de usuario
  - name: Autenticaci贸n
    description: API para autorizaci贸n de usuarios
  - name: Perfil
    description: Perfil del usuario
  - name: Empleados
    description: API para los empleados
schemes:
  - http
paths:
  /register:
    post:
      tags:
        - Registro de nuevo usuario
      summary: Registrar usuario
      description: Registrar un nuevo usuario en el sistema
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Registro de usuario
          description: Registrar un nuevo usuario
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/User"
  /authenticate:
    post:
      tags:
        - Autenticaci贸n
      summary: Autenticar un usuario
      description: Autenticar un usuario para generar el json web token
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Autenticar usuario
          description: Autenticar a un usuario al sistema y generar un token
          required: true
          schema:
            $ref: "#/definitions/Auth"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Auth"
  /profile:
    get:
      tags:
        - Perfil
      summary: Perfil un usuario
      description: Perfil del usuario
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: authorization
          description: Acceder mediante el token
          in: header
          type: string
          required: true
      responses:
        200:
          description: OK
  /employees:
    parameters:
      - name: authorization
        description: Access token to authorize the user
        in: header
        type: string
        required: true
    post:
      tags:
        - Empleados
      summary: Crear un nuevo empleado
      description: Crear un empleado y como respuesta nos debe volver un 201 de creado
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: employee
          description: Crear un nuevo empleado
          required: true
          schema:
            $ref: "#/definitions/Employee"
      responses:
        201:
          description: Created
    get:
      tags:
        - Empleados
      summary: Obtener una lista de empleados
      description: Todos los empleados
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Employees"
definitions:
  User:
    required:
      - fullname
      - email
      - password
    properties:
      _id:
        type: string
      fullname:
        type: string
      email:
        type: string
        format: email
      password:
        type: string
        format: password
  Auth:
    required:
      - email
      - password
    properties:
      email:
        type: string
      password:
        type: string
        format: password
  Employee:
    required:
      - fullName
      - hireDate
      - salary
    properties:
      _id:
        type: string
      fullName:
        type: string
      hireDate:
        type: string
        format: date-time
      isPermanent:
        type: boolean
        default: false
      salary:
        type: number
        format: double
  Employees:
    properties:
      docs:
        type: array
        items:
          $ref: "#/definitions/Employee"
      totalDocs:
        type: integer
        format: int32
      limit:
        type: integer
        format: int32
      totalPages:
        type: integer
        format: int32
      page:
        type: integer
        format: int32
      pagingCounter:
        type: integer
        format: int32
      hasPrevPage:
        type: boolean
      hasNextPage:
        type: boolean
      prevPage:
        type: integer
        format: int32
      nextPage:
        type: integer
        format: int32
externalDocs:
  url: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md
  description: Swagger RESTful API Documentation Specification
